version: '3'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonar-network

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    user: root
    env_file:
      - .env
    platform: linux/amd64
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_SCANNER_OPTS=-Dsonar.projectKey=app_test -Dsonar.projectName=EE-Working -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.login=sqp_09c3e65fe0a42cd69b0c3e59c73936a5ac38f0ca -Dsonar.projectBaseDir=/usr/src -Dsonar.scm.disabled=true
    volumes:
      - ./laravel-sonar-rules/laravel-massige-app:/usr/src:rw
    networks:
      - sonar-network
    depends_on:
      - sonarqube


networks:
  sonar-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"